/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Planeta(props) {
  const { nodes, materials } = useGLTF('/public/models/Planeta.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Planet_10.geometry}
        material={materials.Atlas}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/public/models/Planeta.glb')

