/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plan(props) {
  const { nodes, materials } = useGLTF('/public/models/Planet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Planet_2.geometry} material={materials.Atlas} scale={100} />
    </group>
  )
}

useGLTF.preload('/public/models/Planet.glb')

