/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet(props) {
  const { nodes, materials } = useGLTF('/public/Neptune.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002_1.geometry}
        material={materials['02___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002_1_1.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002_1_2.geometry}
        material={materials['03___Default']}
      />
    </group>
  )
}

useGLTF.preload('/public/Neptune.glb')

