/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sati(props) {
  const { nodes, materials } = useGLTF('/public/models/Sati.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box004_1.geometry}
        material={materials['09___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box004_1_1.geometry}
        material={materials['08___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GeoSphere002_1.geometry}
        material={materials['07___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GeoSphere002_1_1.geometry}
        material={materials['03___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GeoSphere002_1_2.geometry}
        material={materials['02___Default']}
      />
    </group>
  )
}

useGLTF.preload('/public/models/Sati.glb')

